### ISSUE TITLE
Reload command now requires approval and opens new shell

### ISSUE THREAD

**Issue by michaeljolley** [MichaelJolley/ps-alias#38]
Before converting to a module the reload would happen in place.  I believe this is due to the commented out code in the [HelperFunctions.psm1](https://github.com/MichaelJolley/devtoolbox/blob/master/modules/devtoolbox/functions/HelperFunctions.psm1) file.  We need to uncomment that code and get it working again.  

I believe @brettmillerb is the one who initially added it so he may know the best way to implement it now that we're using a module.

**Comment by parithon** [comment]
My understanding is that this feature requires Powershell to spawn another instance of itself when you first launch PowerShell. Then when you `reload` it exists the spawned child process and starts a new one. The problem with this working in a module is that you can't spawn a child instance of PowerShell when loading the module because the module is loading in the 'current' instance not the new instance.

If we are looking for a way to refresh the environment with path and environment variables, perhaps we can mimic the functionality from Chocolatey's '[refreshenv.cmd](https://github.com/chocolatey-archive/chocolatey/blob/master/src/redirects/RefreshEnv.cmd)' file and create a function that refreshes the environment from the registry.
